cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "mas"
brew "mysql"
brew "nodenv"
brew "pv"
brew "rbenv"
brew "unar"
brew "yarn"
brew "zplug"

cask "android-studio"
cask "figma"
cask "firefox"
cask "google-chrome"
cask "google-chrome-canary"
cask "imageoptim"
cask "messenger"
cask "notion"
cask "obs"
cask "react-native-debugger"
cask "shiftit"
cask "virtualbox"
cask "visual-studio-code"
cask "zoom"

mas "1Password", id: 443987910
mas "Amphetamine", id: 937984704
mas "DaisyDisk", id: 411643860
mas "Display Menu", id: 549083868
mas "Genki Arcade", id: 1555925018
mas "JoyKeyMapper", id: 1511416593
mas "JPEGmini", id: 498944723
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "LINE", id: 539883307
mas "Mactracker", id: 430255202
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PNG mini", id: 530839610
mas "Skitch", id: 425955336
mas "Slack", id: 803453959
mas "Transmit", id: 403388562
mas "TweetDeck", id: 485812721
mas "Xcode", id: 497799835
